"""add_users_auth_encryption

Revision ID: 8f86da7bc06a
Revises: 414b737c6855
Create Date: 2026-02-25 20:23:03.731660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8f86da7bc06a'
down_revision: Union[str, None] = '414b737c6855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('fecha_de_nacimiento', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('correo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('salt', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('supabase_uid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('bo_connection', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_correo'), ['correo'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_supabase_uid'), ['supabase_uid'], unique=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_encrypted', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.add_column(sa.Column('answer_encrypted', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.drop_column('answer')
        batch_op.drop_column('question')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('answer_encrypted')
        batch_op.drop_column('question_encrypted')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_supabase_uid'))
        batch_op.drop_index(batch_op.f('ix_users_correo'))

    op.drop_table('users')
    # ### end Alembic commands ###
